### ISSUE TITLE
Can't delete AD Tennant

### ISSUE THREAD

**Issue by fmuntean** [MicrosoftDocs/SupportArticles-docs#283]
Tried this steps and still can't delete the AD Tennant.
See: https://docs.microsoft.com/en-us/answers/comments/547636/view.html

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5e2523-f39f-3dcc-c82b-7c191e999449
* Version Independent ID: 8ee3b0cb-b361-4d5c-e798-8029d81748c5
* Content: [Can't delete a directory through the Azure Management Portal - Active Directory](https://docs.microsoft.com/en-GB/troubleshoot/azure/active-directory/cannot-delete-directory-azure-portal)
* Content Source: [support/azure/active-directory/cannot-delete-directory-azure-portal.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/cannot-delete-directory-azure-portal.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Although this is obviously not a request for support, know that you are not the first person, because this happened to me two years ago. After months of research, I realised that I was one of many. The method that I did use to remediate it was discussion of it with Microsoft Support. They were very efficient and assistive, and ultimately did delete it for me. They also never knew the reason that I was prevented.
