### ISSUE TITLE
Update PerfInsights supported distributions list

### ISSUE THREAD

**Issue by evanzhang89** [MicrosoftDocs/SupportArticles-docs#471]
Hello Team,

Looking at the feedback https://github.com/MicrosoftDocs/azure-docs/issues/66779
It looks like PerInsights do support **RHEL 7.6, 7.7, 7.8, 7.9**, but the document yet got updated. Can you verify and update the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fa2432-67f8-688a-e58a-752b2cb0c2d2
* Version Independent ID: fe34017d-5f11-702f-a15c-9334294650da
* Content: [Performance diagnostics for Azure virtual machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics)
* Content Source: [support/azure/virtual-machines/performance-diagnostics.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/performance-diagnostics.md)
* Service: **virtual-machines**
* GitHub Login: @anandhms
* Microsoft Alias: **anandh**

**Comment by genlin** [comment]
@evanzhang89 Thanks for the comment. I will confirm with our engineers, and get back to you.

**Comment by Klaas-** [comment]
I am guessing you need to look at more distributions as well :)
if you support Oracle Linux 7.9, you should also be okay with CentOS 7.9, they are essentially the same distribution as RHEL 7.9 which is also missing (apart from the Oracle UEK kernel)

Same goes for newer RHEL 8; if you support Alma 8.4 and 8.5 you should also be able to support RHEL 8.4 and 8.5 because alma is a clone/rebuild of RHEL.

**Comment by genlin** [comment]
@Klaas-  We're working on this and the article will be updated soon.

**Comment by Klaas-** [comment]
@genlin https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/performance-diagnostics.md?plain=1#L51-L57 :) RHEL still does not show as supported for 7.9
