### ISSUE TITLE
The Azure AD Connect Provisioning Agent Cannot Be Installed 

### ISSUE THREAD

**Issue by colson05** [MicrosoftDocs/SupportArticles-docs#888]
How can we change the settings for the Azure AD Connect Provisioning Agent if the Agent is not installed?

This support information does not make sense. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38cd2a4d-5257-ff8f-20b9-58de1c91d285
* Version Independent ID: 97071d80-31d3-1592-97ea-8777c203154a
* Content: [Azure AD Hybrid Sync Agent Installation Issues - Cannot start service AADConnectProvisioningAgent - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/azure-ad-hybrid-sync-cannot-start-aadconnect-provisioning-agent)
* Content Source: [support/azure/active-directory/azure-ad-hybrid-sync-cannot-start-aadconnect-provisioning-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/azure-ad-hybrid-sync-cannot-start-aadconnect-provisioning-agent.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@colson05,  In some scenarios, the installation cannot be completed due to the **AADConnectProvisioningAgent** service fails started (the service is installed during the installation). Do you see the " AADConnectProvisioningAgent" service is in **services.msc**(Press windows logo key+R, then type services.msc to run). To resolve this issue quickly, please [contact our support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview?DMC=troubleshoot).
