### ISSUE TITLE
VS 2022 (17.4.4) don't support the Task List feature for NET 6/7 project, but work for Framework projects

### ISSUE THREAD

**Issue by DrCQ** [MicrosoftDocs/SupportArticles-docs#894]
I used the "Task List" feature for my WPF NET Framework projects. Now I created a new WPF NET 6/7 projects and the Task List feature is not working. 
The "Task List" window is empty and the (Entire Solution/Current Project/Current Document/Open Documents) drop-down in the left-upper corner is empty.

**Comment by HaiyingYu** [comment]
Hi, @DrCQ. If you want to ask questions to our products instead of providing feedback to articles in this repository, you can go to   forums or contact Microsoft Support for help. I will close the issue at this time. If you have questions or further feedback to our articles, feel free to create a new Issue/PR. Thanks!
